# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        working-directory: ./server
        with:
          node-version: 22.x
          cache: "npm"
      - name: "Install"
        run: npm ci
        working-directory: ./server
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        working-directory: ./client
        with:
          node-version: 22.x
          cache: "npm"
      - name: "Install"
        run: npm ci
        working-directory: ./client
      - name: "Build"
        run: npm run build
        working-directory: ./client
